name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x, 18.x, 19.x]

    steps:
      - uses: actions/checkout@v3
          
      - name: Install modules
        run: npm ci
      
      - name: Build project
        run: npm run build --if-present
